stages:
  - build
  - py-build
  - test
  - doc

build:
  stage: build
  image: rust:1.89-bullseye
  before_script:
    - apt update -y
    - apt install cmake clang -y
  script: 
    - cargo build --no-default-features

rustdoc:
  stage: doc
  dependencies: [build]
  image: rust:1.89-bullseye
  before_script:
    - apt update -y
    - apt install cmake clang -y
  script: 
    - cargo doc --no-default-features

test:
  stage: test
  dependencies: [build]
  image: rust:1.89-bullseye
  before_script:
    - apt update -y
    - apt install cmake clang -y
  script:
    - cargo test --no-default-features

py-build:
  stage: py-build
  image: rust:1.89-bullseye
  before_script:
    - apt update -y
    - apt install cmake clang -y
    - apt install python3.10
  script: 
    - cargo build --no-default-features
    - pip install maturin[patchelf]
    - maturin build
  artifacts:


