#[derive(PartialEq, Eq, Debug, Clone, Copy, Hash)]
#[rustfmt::skip]
pub enum Element {
    //   1   2                                                           3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
        H,                                                                                                                          He,
        Li, Be,                                                                                                 B,  C,  N,  O,  F,  Ne,
        Na, Mg,                                                                                                 Al, Si, P,  S,  Cl, Ar,
        K,  Ca,                                                         Sc, Ti, V,  Cr, Mn, Fe, Co, Ni, Cu, Zn, Ga, Ge, As, Se, Br, Kr,
        Rb, Sr,                                                         Y,  Zr, Nb, Mo, Tc, Ru, Rh, Pd, Ag, Cd, In, Sn, Sb, Te, I,  Xe,
        Cs, Ba, La, Ce, Pr, Nd, Pm, Sm, Eu, Gd, Tb, Dy, Ho, Er, Tm, Yb, Lu, Hf, Ta, W,  Re, Os, Ir, Pt, Au, Hg, Tl, Pb, Bi, Po, At, Rn,
        Fr, Ra, Ac, Th, Pa, U,  Np, Pu, Am, Cm, Bk, Cf, Es, Fm, Md, No, Lr, Rf, Db, Sg, Bh, Hs, Mt, Ds, Rg, Cn, Nh, Fl, Mc, Lv, Ts, Og,
}

impl std::fmt::Display for Element {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

impl Element {
    /// return atomic number
    /// ```
    /// use yaxs::element::Element;
    ///
    /// assert_eq!(Element::H.z(), 1);
    /// assert_eq!(Element::He.z(), 2);
    /// assert_eq!(Element::Li.z(), 3);
    /// assert_eq!(Element::Db.z(), 105);
    /// ```
    pub fn z(&self) -> u8 {
        *self as u8 + 1
    }

    /// return the atomic weight  
    ///
    /// this implements data from table 2 provided at
    /// <https://iupac.qmul.ac.uk/AtWt/index.html>
    /// with the relevant papers being
    ///
    /// Standard atomic weights of the elements 2021 (IUPAC Technical Report)
    /// <https://doi.org/10.1515/pac-2019-0603>
    ///
    /// <https://iupac.org/standard-atomic-weights-of-three-technology-critical-elements-revised/>
    ///
    pub fn atomic_weight(&self) -> f64 {
        use Element::*;
        match self {
            H => 1.0080,
            He => 4.002,
            Li => 6.94,
            Be => 9.012,
            B => 10.81,
            C => 12.011,
            N => 14.007,
            O => 15.999,
            F => 18.998,
            Ne => 20.1797,
            Na => 22.989,
            Mg => 24.305,
            Al => 26.981,
            Si => 28.085,
            P => 30.973,
            S => 32.06,
            Cl => 35.45,
            Ar => 39.95,
            K => 39.0983,
            Ca => 40.078,
            Sc => 44.955,
            Ti => 47.867,
            V => 50.9415,
            Cr => 51.9961,
            Mn => 54.938,
            Fe => 55.845,
            Co => 58.933,
            Ni => 58.6934,
            Cu => 63.546,
            Zn => 65.38,
            Ga => 69.723,
            Ge => 72.630,
            As => 74.921,
            Se => 78.971,
            Br => 79.904_,
            Kr => 83.798,
            Rb => 85.4678,
            Sr => 87.62,
            Y => 88.905,
            Zr => 91.222,
            Nb => 92.906,
            Mo => 95.95,
            Tc => 97.0,
            Ru => 101.07,
            Rh => 102.905,
            Pd => 106.42,
            Ag => 107.8682,
            Cd => 112.414,
            In => 114.818,
            Sn => 118.710,
            Sb => 121.760,
            Te => 127.60,
            I => 126.904,
            Xe => 131.293,
            Cs => 132.905,
            Ba => 137.327,
            La => 138.905,
            Ce => 140.116,
            Pr => 140.907,
            Nd => 144.242,
            Pm => 145.0,
            Sm => 150.36,
            Eu => 151.964,
            Gd => 157.249,
            Tb => 158.925,
            Dy => 162.500,
            Ho => 164.930,
            Er => 167.259,
            Tm => 168.934,
            Yb => 173.045,
            Lu => 174.966,
            Hf => 178.486,
            Ta => 180.947,
            W => 183.84,
            Re => 186.207,
            Os => 190.23,
            Ir => 192.217,
            Pt => 195.084,
            Au => 196.966,
            Hg => 200.592,
            Tl => 204.38,
            Pb => 207.2,
            Bi => 208.980,
            Po => 209.0,
            At => 210.0,
            Rn => 222.0,
            Fr => 223.0,
            Ra => 226.0,
            Ac => 227.0,
            Th => 232.0377,
            Pa => 231.035,
            U => 238.028,
            Np => 237.0,
            Pu => 244.0,
            Am => 243.0,
            Cm => 247.0,
            Bk => 247.0,
            Cf => 251.0,
            Es => 252.0,
            Fm => 257.0,
            Md => 258.0,
            No => 259.0,
            Lr => 262.0,
            Rf => 267.0,
            Db => 270.0,
            Sg => 269.0,
            Bh => 270.0,
            Hs => 270.0,
            Mt => 278.0,
            Ds => 281.0,
            Rg => 281.0,
            Cn => 285.0,
            Nh => 286.0,
            Fl => 289.0,
            Mc => 289.0,
            Lv => 293.0,
            Ts => 293.0,
            Og => 294.0,
        }
    }
}

impl TryFrom<&str> for Element {
    type Error = String;

    fn try_from(val: &str) -> Result<Self, Self::Error> {
        use Element::*;
        let el = match val {
            "H" => H,
            "He" => He,
            "Li" => Li,
            "Be" => Be,
            "B" => B,
            "C" => C,
            "N" => N,
            "O" => O,
            "F" => F,
            "Ne" => Ne,
            "Na" => Na,
            "Mg" => Mg,
            "Al" => Al,
            "Si" => Si,
            "P" => P,
            "S" => S,
            "Cl" => Cl,
            "Ar" => Ar,
            "K" => K,
            "Ca" => Ca,
            "Sc" => Sc,
            "Ti" => Ti,
            "V" => V,
            "Cr" => Cr,
            "Mn" => Mn,
            "Fe" => Fe,
            "Co" => Co,
            "Ni" => Ni,
            "Cu" => Cu,
            "Zn" => Zn,
            "Ga" => Ga,
            "Ge" => Ge,
            "As" => As,
            "Se" => Se,
            "Br" => Br,
            "Kr" => Kr,
            "Rb" => Rb,
            "Sr" => Sr,
            "Y" => Y,
            "Zr" => Zr,
            "Nb" => Nb,
            "Mo" => Mo,
            "Tc" => Tc,
            "Ru" => Ru,
            "Rh" => Rh,
            "Pd" => Pd,
            "Ag" => Ag,
            "Cd" => Cd,
            "In" => In,
            "Sn" => Sn,
            "Sb" => Sb,
            "Te" => Te,
            "I" => I,
            "Xe" => Xe,
            "Cs" => Cs,
            "Ba" => Ba,
            "La" => La,
            "Ce" => Ce,
            "Pr" => Pr,
            "Nd" => Nd,
            "Pm" => Pm,
            "Sm" => Sm,
            "Eu" => Eu,
            "Gd" => Gd,
            "Tb" => Tb,
            "Dy" => Dy,
            "Ho" => Ho,
            "Er" => Er,
            "Tm" => Tm,
            "Yb" => Yb,
            "Lu" => Lu,
            "Hf" => Hf,
            "Ta" => Ta,
            "W" => W,
            "Re" => Re,
            "Os" => Os,
            "Ir" => Ir,
            "Pt" => Pt,
            "Au" => Au,
            "Hg" => Hg,
            "Tl" => Tl,
            "Pb" => Pb,
            "Bi" => Bi,
            "Po" => Po,
            "At" => At,
            "Rn" => Rn,
            "Fr" => Fr,
            "Ra" => Ra,
            "Ac" => Ac,
            "Th" => Th,
            "Pa" => Pa,
            "U" => U,
            "Np" => Np,
            "Pu" => Pu,
            "Am" => Am,
            "Cm" => Cm,
            "Bk" => Bk,
            "Cf" => Cf,
            "Es" => Es,
            "Fm" => Fm,
            "Md" => Md,
            "No" => No,
            "Lr" => Lr,
            "Rf" => Rf,
            "Db" => Db,
            "Sg" => Sg,
            "Bh" => Bh,
            "Hs" => Hs,
            "Mt" => Mt,
            "Ds" => Ds,
            "Rg" => Rg,
            "Cn" => Cn,
            "Nh" => Nh,
            "Fl" => Fl,
            "Mc" => Mc,
            "Lv" => Lv,
            "Ts" => Ts,
            "Og" => Og,
            _ => return Err(format!("Invalid Element Symbol '{val}'")),
        };
        Ok(el)
    }
}
